### ISSUE TITLE
Down website not handled correctly

### ISSUE THREAD

**Issue by tvqt** [SebRollen/AdventOfCode.jl#34] opened 2023-02-23 05:35 UTC
The website is currently down:
![Screen Shot 2023-02-23 at 19 33 19](https://user-images.githubusercontent.com/12098500/220828265-1a7cc82d-5b06-479c-9d48-3f4e4a8e1879.png)

Running the package at this time leads to the input file being the HTML of the website down page:
`<!DOCTYPE html>
<html lang="en-us"><head><meta charset="utf-8"/><title>Advent of Code</title><link href='//fonts.googleapis.com/css?family=Source+Code+Pro:300&subset=latin,latin-ext' rel='stylesheet' type='text/css'><style>body { background: #0f0f23; color: #cccccc; font-family: "Source Code Pro", monospace; font-size: 14pt; } #message { text-align: center; position: fixed; top: 50%; margin-top: -1.9em; white-space: pre; width: 100%; }</style></head><body><div id="message">.----------------------.
| We'll be right back! |
'----------------------'</div></body></html>
`
A case to handle, return an error perhaps?

**Comment by SebRollen** [comment] 2024-12-03 02:56
Sorry for the (very) late reply to this!

Closing this as a wont-fix as this tool is pretty bare-bones by design, and it'll be pretty clear to the user that something is up as soon as they inspect the file

**Closed as not planned by SebRollen** 2024-12-03 02:56 UTC
